{
 "title": "Geth Server",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Block",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth-node_block" }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth-node_block_transactions", "legendFormat": "Transactions" }
   ]
  },
  {
   "title": "Ether Transfers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth-node_eth_transfers", "legendFormat": "ETH" },
    { "expr": "geth-node_token_transfers", "legendFormat": "Tokens" }
   ]
  },
  {
   "title": "ETH Value",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth-node_block_value" }
   ]
  },
  {
   "title": "Since Last Block",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "geth-node_seconds_last_block" }
   ]
  },
  {
   "title": "ETH Transfers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth-node_eth_transfers", "legendFormat": "ETH Transfers" }
   ]
  },
  {
   "title": "ETH Transfers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth-node_eth_transfers" }
   ]
  },
  {
   "title": "Token Transfers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth-node_token_transfers" }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "geth-node_pending_transactions" }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "geth-node_block_size_bytes", "legendFormat": "Token Transfers" }
   ]
  },
  {
   "title": "Gas Price (gwei)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geth-node_gas_price / 1000000000",
     "legendFormat": "Gas Price"
    }
   ]
  },
  {
   "title": "Gas Price",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "geth-node_gas_price / 1000000000"
    }
   ]
  },
  {
   "title": "Block Difficulty",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth-node_block_difficulty / 10000000000000",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Block Nonce",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "geth-node_block_nonce / 1000000000000000000",
     "legendFormat": "Nonce"
    }
   ]
  },
  {
   "title": "Gas Used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geth-node_block_gas_used", "legendFormat": "Token Transfers" }
   ]
  },
  {
   "title": "Contracts Created",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth-node_contracts_created", "legendFormat": "Contracts" }
   ]
  },
  {
   "title": "Response Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "geth-node_load_time" }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth-node_pending_transactions", "legendFormat": "transactions" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "content": "<p align=\"center\" style=\"font-size:30pt\">Today Totals</p>"
  },
  {
   "title": "Today's Sent ETH",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 28 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    { "expr": "sum(geth-node_block_value)" }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 28 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "geth-node_block_transactions", "legendFormat": "Transactions" }
   ]
  }
 ]
}